/* The following code was generated by JFlex 1.7.0 */

package analizadores;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>LexicalAnalyzer.jflex</tt>
 */
public class Lexical_Analyzer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 15, 51, 49, 49,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    50,  0,  4,  0, 12,  0,  0,  5, 37, 38, 11, 33, 42, 34,  2, 10, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 41,  0,  0, 47, 19, 
     0, 29, 46, 22, 28, 26, 24, 44, 48, 21, 17, 17, 30, 36,  8, 23, 
    35, 17, 27, 32,  9, 45, 25, 17, 17, 43, 17, 39,  7, 40,  0, 16, 
     0, 29, 46, 22, 28, 26, 24, 44, 48, 21, 17, 17, 30, 36,  8, 23, 
    35, 17, 27, 32,  9, 45, 25, 17, 17, 43, 17, 13,  3, 14,  0,  0, 
     0,  0,  0,  0,  0, 51,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 
     0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\11\1\1\10\1\11\2\1\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\2\1\2\0\1\20"+
    "\1\0\1\21\4\0\1\22\6\0\1\23\7\0\1\24"+
    "\1\0\1\25\10\0\1\26\1\21\1\0\1\27\2\0"+
    "\1\30\3\0\1\31\4\0\1\32\5\0\1\33\4\0"+
    "\1\34\7\0\1\35\4\0\1\36\2\0\1\37\11\0"+
    "\1\40\21\0\1\41\5\0\1\42\2\0\1\43\1\44"+
    "\1\0\1\45\1\46\1\47\1\50\1\51\4\0\1\52"+
    "\1\53\35\0\1\54\1\0\1\55\1\0\1\56\1\0"+
    "\1\57\2\0\1\60\1\61\2\0\1\62\1\63\3\0"+
    "\1\64\1\65\1\0\1\66\12\0\1\67\5\0\1\70"+
    "\1\71\4\0\1\72\1\73\1\0\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\64\0\u0104\0\u0138"+
    "\0\64\0\u016c\0\64\0\64\0\u01a0\0\u01d4\0\u0208\0\u023c"+
    "\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340\0\64\0\u0374\0\u03a8"+
    "\0\u03dc\0\64\0\64\0\64\0\64\0\64\0\64\0\u0410"+
    "\0\u0444\0\u0478\0\234\0\64\0\u04ac\0\64\0\u04e0\0\u0514"+
    "\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4"+
    "\0\u06e8\0\64\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\64\0\u0888\0\64\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0478\0\u04ac\0\u0a5c\0\64"+
    "\0\u0a90\0\u0ac4\0\64\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68"+
    "\0\u0d9c\0\64\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\64\0\u0ea0"+
    "\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\64\0\u100c"+
    "\0\u1040\0\u1074\0\u10a8\0\64\0\u10dc\0\u1110\0\64\0\u1144"+
    "\0\u1178\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4"+
    "\0\64\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450"+
    "\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0"+
    "\0\u1624\0\u1658\0\64\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c"+
    "\0\64\0\u1790\0\u17c4\0\u17f8\0\u182c\0\u1860\0\64\0\64"+
    "\0\64\0\64\0\64\0\u1894\0\u18c8\0\u18fc\0\u1930\0\64"+
    "\0\64\0\u1964\0\u1998\0\u19cc\0\u1a00\0\u1a34\0\u1a68\0\u1a9c"+
    "\0\u1ad0\0\u1b04\0\u1b38\0\u1b6c\0\u1ba0\0\u1bd4\0\u1c08\0\u1c3c"+
    "\0\u1c70\0\u1ca4\0\u1cd8\0\u1d0c\0\u1d40\0\u1d74\0\u1da8\0\u1ddc"+
    "\0\u1e10\0\u1e44\0\u1e78\0\u1eac\0\u1ee0\0\u1f14\0\64\0\u1f48"+
    "\0\64\0\u1f7c\0\64\0\u1fb0\0\64\0\u1fe4\0\u2018\0\64"+
    "\0\64\0\u204c\0\u2080\0\64\0\64\0\u20b4\0\u20e8\0\u211c"+
    "\0\64\0\64\0\u2150\0\64\0\u2184\0\u21b8\0\u21ec\0\u2220"+
    "\0\u2254\0\u2288\0\u22bc\0\u22f0\0\u2324\0\u2358\0\64\0\u238c"+
    "\0\u23c0\0\u23f4\0\u2428\0\u245c\0\64\0\64\0\u2490\0\u24c4"+
    "\0\u24f8\0\u252c\0\64\0\64\0\u2560\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\5\1\6\1\2\1\7"+
    "\1\2\1\10\1\11\3\2\1\6\1\12\1\2\1\13"+
    "\1\14\2\15\1\16\1\17\1\20\1\21\1\22\1\2"+
    "\1\23\1\24\1\2\2\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\3\2\1\40"+
    "\1\2\1\41\2\6\66\0\1\3\1\42\61\0\4\43"+
    "\1\44\57\43\4\45\1\0\1\46\1\0\1\47\4\45"+
    "\1\50\2\45\1\0\44\45\27\0\1\51\25\0\1\52"+
    "\20\0\1\53\1\54\51\0\1\55\6\0\2\55\7\0"+
    "\1\55\3\0\12\55\1\0\1\55\2\0\2\55\6\0"+
    "\4\55\1\0\1\55\13\0\1\56\102\0\1\57\5\0"+
    "\1\60\46\0\1\61\12\0\1\62\54\0\2\63\7\0"+
    "\1\64\60\0\1\65\41\0\1\66\26\0\2\67\55\0"+
    "\1\70\41\0\1\71\77\0\2\72\4\0\1\73\110\0"+
    "\1\74\33\0\1\75\5\0\1\76\52\0\2\77\1\0"+
    "\1\100\2\0\1\101\2\0\1\102\55\0\1\103\71\0"+
    "\1\104\27\0\1\105\1\0\1\105\56\0\1\105\6\0"+
    "\1\46\62\0\1\45\1\106\2\0\2\45\57\0\1\46"+
    "\7\0\1\107\57\0\1\110\116\0\1\111\17\0\17\53"+
    "\1\0\44\53\13\54\1\112\50\54\1\0\1\55\6\0"+
    "\2\55\6\0\1\113\1\55\3\0\12\55\1\0\1\55"+
    "\2\0\2\55\6\0\4\55\1\0\1\55\27\0\2\114"+
    "\1\115\25\0\1\116\17\0\1\117\33\0\1\120\52\0"+
    "\1\121\1\122\66\0\2\123\33\0\1\124\111\0\1\125"+
    "\60\0\1\126\41\0\1\127\72\0\1\130\63\0\1\131"+
    "\77\0\1\132\103\0\1\133\20\0\1\134\105\0\1\135"+
    "\62\0\1\136\65\0\1\137\37\0\1\140\126\0\1\141"+
    "\37\0\1\142\62\0\1\143\10\0\2\144\24\0\1\145"+
    "\114\0\1\146\31\0\12\54\1\147\1\112\50\54\26\0"+
    "\1\150\70\0\1\151\63\0\1\152\50\0\1\153\72\0"+
    "\1\154\71\0\1\155\60\0\1\156\55\0\2\157\56\0"+
    "\1\160\102\0\2\161\57\0\1\162\56\0\1\163\60\0"+
    "\2\164\6\0\1\165\65\0\1\166\102\0\1\167\40\0"+
    "\1\170\66\0\1\171\36\0\1\172\102\0\1\173\63\0"+
    "\1\174\72\0\1\175\57\0\1\176\42\0\1\177\53\0"+
    "\1\145\14\0\1\200\100\0\1\201\54\0\2\202\70\0"+
    "\1\203\63\0\1\204\62\0\1\205\60\0\1\206\45\0"+
    "\1\207\112\0\2\210\2\0\1\211\1\212\46\0\1\213"+
    "\71\0\1\214\36\0\1\215\127\0\1\216\33\0\2\217"+
    "\65\0\1\220\44\0\1\221\63\0\1\222\64\0\1\223"+
    "\105\0\1\224\63\0\1\225\62\0\1\226\64\0\1\227"+
    "\65\0\1\230\33\0\1\231\105\0\1\232\63\0\1\233"+
    "\100\0\1\234\56\0\2\235\60\0\1\236\37\0\1\237"+
    "\107\0\1\240\52\0\2\241\4\0\1\242\66\0\1\243"+
    "\52\0\2\244\72\0\1\245\55\0\1\246\112\0\1\247"+
    "\36\0\1\250\53\0\1\251\71\0\1\252\70\0\1\253"+
    "\50\0\1\254\63\0\1\255\100\0\1\256\60\0\1\257"+
    "\66\0\1\260\64\0\1\261\57\0\1\262\105\0\1\263"+
    "\42\0\1\264\62\0\1\265\63\0\1\266\63\0\1\267"+
    "\66\0\1\270\60\0\1\271\57\0\1\272\61\0\2\273"+
    "\73\0\1\274\55\0\1\275\63\0\1\276\44\0\1\277"+
    "\63\0\1\300\106\0\1\301\57\0\1\302\67\0\1\303"+
    "\105\0\1\304\43\0\1\305\36\0\1\306\106\0\1\307"+
    "\67\0\2\310\61\0\1\311\60\0\1\312\57\0\1\313"+
    "\71\0\1\314\65\0\2\315\43\0\1\316\63\0\1\317"+
    "\54\0\1\320\105\0\1\321\40\0\1\322\64\0\1\323"+
    "\101\0\1\324\66\0\1\325\41\0\1\326\77\0\2\327"+
    "\62\0\2\330\73\0\1\331\61\0\1\332\40\0\1\333"+
    "\64\0\1\334\126\0\1\335\63\0\1\336\45\0\1\337"+
    "\62\0\1\340\37\0\1\341\105\0\1\342\105\0\1\343"+
    "\63\0\1\344\45\0\2\345\55\0\1\346\66\0\1\347"+
    "\63\0\1\350\63\0\1\351\61\0\1\352\66\0\1\353"+
    "\63\0\1\354\51\0\2\355\65\0\1\356\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9620];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\1\11\1\1\2\11"+
    "\11\1\1\11\3\1\6\11\2\1\2\0\1\11\1\0"+
    "\1\11\4\0\1\1\6\0\1\11\7\0\1\11\1\0"+
    "\1\11\10\0\2\1\1\0\1\11\2\0\1\11\3\0"+
    "\1\1\4\0\1\1\5\0\1\11\4\0\1\11\7\0"+
    "\1\11\4\0\1\11\2\0\1\11\11\0\1\11\21\0"+
    "\1\11\5\0\1\11\2\0\2\1\1\0\5\11\4\0"+
    "\2\11\35\0\1\11\1\0\1\11\1\0\1\11\1\0"+
    "\1\11\2\0\2\11\2\0\2\11\3\0\2\11\1\0"+
    "\1\11\12\0\1\11\5\0\2\11\4\0\2\11\1\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexical_Analyzer(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico : "+yytext()+ "Linea"+(yyline+1)+" Columna "+yycolumn);
            } 
            // fall through
          case 61: break;
          case 2: 
            { System.out.println("Reconocio token:<entero> lexema:"+yytext());
                      return new Symbol(Simbolos.nEntero, yycolumn, yyline, yytext());
            } 
            // fall through
          case 62: break;
          case 3: 
            { /*este es un comentario en java, omitirlos*/
            } 
            // fall through
          case 63: break;
          case 4: 
            { System.out.println("Reconocio token: <div> lexema: "+yytext()); 
              return new Symbol(Simbolos.div, yycolumn, yyline, yytext());
            } 
            // fall through
          case 64: break;
          case 5: 
            { System.out.println("Reconocio token: <per> lexema: "+yytext()); 
              return new Symbol(Simbolos.per, yycolumn, yyline, yytext());
            } 
            // fall through
          case 65: break;
          case 6: 
            { System.out.println("Reconocio token: <tkInterLeft> lexema: "+yytext()); 
              return new Symbol(Simbolos.tkInterLeft, yycolumn, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 7: 
            { System.out.println("Reconocio token: <tkInterRight> lexema: "+yytext()); 
              return new Symbol(Simbolos.tkInterRight, yycolumn, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 8: 
            { System.out.println("Reconocio token: <plus> lexema: "+yytext()); 
              return new Symbol(Simbolos.plus, yycolumn, yyline, yytext());
            } 
            // fall through
          case 68: break;
          case 9: 
            { System.out.println("Reconocio token: <minus> lexema: "+yytext()); 
              return new Symbol(Simbolos.minus, yycolumn, yyline, yytext());
            } 
            // fall through
          case 69: break;
          case 10: 
            { System.out.println("Reconocio token: <leftPar> lexema: "+yytext()); 
              return new Symbol(Simbolos.leftPar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 70: break;
          case 11: 
            { System.out.println("Reconocio token: <rightPar> lexema: "+yytext()); 
              return new Symbol(Simbolos.rightPar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 71: break;
          case 12: 
            { System.out.println("Reconocio token: <leftCor> lexema: "+yytext()); 
              return new Symbol(Simbolos.leftCor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 72: break;
          case 13: 
            { System.out.println("Reconocio token: <rightCor> lexema: "+yytext()); 
              return new Symbol(Simbolos.rightCor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 73: break;
          case 14: 
            { System.out.println("Reconocio token: <dotComma> lexema: "+yytext()); 
              return new Symbol(Simbolos.dotComma, yycolumn, yyline, yytext());
            } 
            // fall through
          case 74: break;
          case 15: 
            { System.out.println("Reconocio token: <comma> lexema: "+yytext()); 
              return new Symbol(Simbolos.comma, yycolumn, yyline, yytext());
            } 
            // fall through
          case 75: break;
          case 16: 
            { System.out.println("Reconocio token:<cadena> lexema: "+yytext());
                     return new Symbol(Simbolos.cadena, yycolumn, yyline, yytext());
            } 
            // fall through
          case 76: break;
          case 17: 
            { System.out.println("Reconocio token:<charNormal> lexema: "+yytext());
                     return new Symbol(Simbolos.charNormal, yycolumn, yyline, yytext());
            } 
            // fall through
          case 77: break;
          case 18: 
            { System.out.println("Reconocio token:<comment> lexema: "+yytext());
                     return new Symbol(Simbolos.comment, yycolumn, yyline, yytext());
            } 
            // fall through
          case 78: break;
          case 19: 
            { System.out.println("Reconocio token: <or> lexema: "+yytext()); 
              return new Symbol(Simbolos.prOr, yycolumn, yyline, yytext());
            } 
            // fall through
          case 79: break;
          case 20: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prIf, yycolumn, yyline, yytext());
            } 
            // fall through
          case 80: break;
          case 21: 
            { System.out.println("Reconocio token: <tkAsignar> lexema: "+yytext()); 
              return new Symbol(Simbolos.tkAsignar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 81: break;
          case 22: 
            { System.out.println("Reconocio token:<decimal> lexema:"+yytext());
                     return new Symbol(Simbolos.nDecimal, yycolumn, yyline, yytext());
            } 
            // fall through
          case 82: break;
          case 23: 
            { System.out.println("Reconocio token: <not> lexema: "+yytext()); 
              return new Symbol(Simbolos.prNot, yycolumn, yyline, yytext());
            } 
            // fall through
          case 83: break;
          case 24: 
            { System.out.println("Reconocio token:<varName> lexema: "+yytext());
                     return new Symbol(Simbolos.varName, yycolumn, yyline, yytext());
            } 
            // fall through
          case 84: break;
          case 25: 
            { System.out.println("Reconocio palabra_reservada 'con', lexema:"+yytext());
              return new Symbol(Simbolos.prCon, yycolumn, yyline, yytext());
            } 
            // fall through
          case 85: break;
          case 26: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
                    return new Symbol(Simbolos.prFin, yycolumn, yyline, yytext());
            } 
            // fall through
          case 86: break;
          case 27: 
            { System.out.println("Reconocio token: <and> lexema: "+yytext()); 
              return new Symbol(Simbolos.prAnd, yycolumn, yyline, yytext());
            } 
            // fall through
          case 87: break;
          case 28: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prMod, yycolumn, yyline, yytext());
            } 
            // fall through
          case 88: break;
          case 29: 
            { System.out.println("Reconocio token:<multiline> lexema: "+yytext());
                     return new Symbol(Simbolos.multiline, yycolumn, yyline, yytext());
            } 
            // fall through
          case 89: break;
          case 30: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prComo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 90: break;
          case 31: 
            { System.out.println("Reconocio palabra_reservada 'o_si', lexema:"+yytext());
              return new Symbol(Simbolos.prElseIf, yycolumn, yyline, yytext());
            } 
            // fall through
          case 91: break;
          case 32: 
            { System.out.println("Reconocio palabra_reservada 'Para', lexema:"+yytext());
              return new Symbol(Simbolos.prFor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 92: break;
          case 33: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext()); 
                    return new Symbol(Simbolos.prFalse, yycolumn, yyline, yytext());
            } 
            // fall through
          case 93: break;
          case 34: 
            { System.out.println("Reconocio palabra_reservada 'segun', lexema:"+yytext());
              return new Symbol(Simbolos.prSegun, yycolumn, yyline, yytext());
            } 
            // fall through
          case 94: break;
          case 35: 
            { System.out.println("Reconocio token: <menor> lexema: "+yytext()); 
              return new Symbol(Simbolos.menor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 95: break;
          case 36: 
            { System.out.println("Reconocio token: <mayor> lexema: "+yytext()); 
              return new Symbol(Simbolos.mayor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 96: break;
          case 37: 
            { System.out.println("Reconocio palabra_reservada 'hacer', lexema:"+yytext());
              return new Symbol(Simbolos.prHacer, yycolumn, yyline, yytext());
            } 
            // fall through
          case 97: break;
          case 38: 
            { System.out.println("Reconocio palabra_reservada 'hasta', lexema:"+yytext());
              return new Symbol(Simbolos.prHasta, yycolumn, yyline, yytext());
            } 
            // fall through
          case 98: break;
          case 39: 
            { System.out.println("Reconocio token:<charAscii> lexema: "+yytext());
                     return new Symbol(Simbolos.charAscii, yycolumn, yyline, yytext());
            } 
            // fall through
          case 99: break;
          case 40: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prNumber, yycolumn, yyline, yytext());
            } 
            // fall through
          case 100: break;
          case 41: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext()); 
                    return new Symbol(Simbolos.prInicio, yycolumn, yyline, yytext());
            } 
            // fall through
          case 101: break;
          case 42: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prChain, yycolumn, yyline, yytext());
            } 
            // fall through
          case 102: break;
          case 43: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prEndIf, yycolumn, yyline, yytext());
            } 
            // fall through
          case 103: break;
          case 44: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prBoolean, yycolumn, yyline, yytext());
            } 
            // fall through
          case 104: break;
          case 45: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prIngresar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 105: break;
          case 46: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prChar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 106: break;
          case 47: 
            { System.out.println("Reconocio palabra_reservada 'Fin Para', lexema:"+yytext());
              return new Symbol(Simbolos.prEndFor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 107: break;
          case 48: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prEntonces, yycolumn, yyline, yytext());
            } 
            // fall through
          case 108: break;
          case 49: 
            { System.out.println("Reconocio token: <equals> lexema: "+yytext()); 
              return new Symbol(Simbolos.equals, yycolumn, yyline, yytext());
            } 
            // fall through
          case 109: break;
          case 50: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prExponent, yycolumn, yyline, yytext());
            } 
            // fall through
          case 110: break;
          case 51: 
            { System.out.println("Reconocio palabra_reservada 'mientras', lexema:"+yytext());
              return new Symbol(Simbolos.prWhile, yycolumn, yyline, yytext());
            } 
            // fall through
          case 111: break;
          case 52: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prConValor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 112: break;
          case 53: 
            { System.out.println("Reconocio palabra_reservada 'fin segun', lexema:"+yytext());
              return new Symbol(Simbolos.prEndSegun, yycolumn, yyline, yytext());
            } 
            // fall through
          case 113: break;
          case 54: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext()); 
                    return new Symbol(Simbolos.prTrue, yycolumn, yyline, yytext());
            } 
            // fall through
          case 114: break;
          case 55: 
            { System.out.println("Reconocio palabra_reservada 'incremental', lexema:"+yytext());
              return new Symbol(Simbolos.prIncremental, yycolumn, yyline, yytext());
            } 
            // fall through
          case 115: break;
          case 56: 
            { System.out.println("Reconocio palabra_reservada 'Fin mientras', lexema:"+yytext());
              return new Symbol(Simbolos.prEndWhile, yycolumn, yyline, yytext());
            } 
            // fall through
          case 116: break;
          case 57: 
            { System.out.println("Reconocio token: <notEquals> lexema: "+yytext()); 
              return new Symbol(Simbolos.notEquals, yycolumn, yyline, yytext());
            } 
            // fall through
          case 117: break;
          case 58: 
            { System.out.println("Reconocio token: <menorigual> lexema: "+yytext()); 
                return new Symbol(Simbolos.menorigual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 118: break;
          case 59: 
            { System.out.println("Reconocio token: <mayorigual> lexema: "+yytext()); 
              return new Symbol(Simbolos.mayorigual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 119: break;
          case 60: 
            { System.out.println("Reconocio palabra_reservada, lexema:"+yytext());
              return new Symbol(Simbolos.prElse, yycolumn, yyline, yytext());
            } 
            // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
