
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int charNormal = 10;
  public static final int prIngresar = 29;
  public static final int plus = 12;
  public static final int minus = 13;
  public static final int prChar = 34;
  public static final int multiline = 11;
  public static final int tkAsignar = 42;
  public static final int comma = 38;
  public static final int prExponent = 16;
  public static final int rightCor = 40;
  public static final int varName = 39;
  public static final int nEntero = 4;
  public static final int rightPar = 19;
  public static final int prConValor = 35;
  public static final int menor = 21;
  public static final int EOF = 0;
  public static final int nDecimal = 5;
  public static final int prComo = 30;
  public static final int error = 1;
  public static final int prNumber = 31;
  public static final int equals = 24;
  public static final int mayor = 20;
  public static final int prBoolean = 33;
  public static final int menorigual = 23;
  public static final int prFin = 3;
  public static final int comment = 36;
  public static final int prTrue = 7;
  public static final int prNot = 28;
  public static final int prAnd = 27;
  public static final int prFalse = 8;
  public static final int mayorigual = 22;
  public static final int prOr = 26;
  public static final int prChain = 32;
  public static final int prInicio = 2;
  public static final int per = 14;
  public static final int notEquals = 25;
  public static final int div = 15;
  public static final int leftCor = 41;
  public static final int prMod = 17;
  public static final int charAscii = 9;
  public static final int dotComma = 37;
  public static final int cadena = 6;
  public static final int leftPar = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "prInicio",
  "prFin",
  "nEntero",
  "nDecimal",
  "cadena",
  "prTrue",
  "prFalse",
  "charAscii",
  "charNormal",
  "multiline",
  "plus",
  "minus",
  "per",
  "div",
  "prExponent",
  "prMod",
  "leftPar",
  "rightPar",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "equals",
  "notEquals",
  "prOr",
  "prAnd",
  "prNot",
  "prIngresar",
  "prComo",
  "prNumber",
  "prChain",
  "prBoolean",
  "prChar",
  "prConValor",
  "comment",
  "dotComma",
  "comma",
  "varName",
  "rightCor",
  "leftCor",
  "tkAsignar"
  };
}

