
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int rightPar = 17;
  public static final int cadena = 6;
  public static final int minus = 11;
  public static final int nEntero = 4;
  public static final int nDecimal = 5;
  public static final int prFalse = 8;
  public static final int prFin = 3;
  public static final int prMod = 15;
  public static final int prTrue = 7;
  public static final int charNormal = 9;
  public static final int div = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int plus = 10;
  public static final int prExponent = 14;
  public static final int per = 12;
  public static final int leftPar = 16;
  public static final int prInicio = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "prInicio",
  "prFin",
  "nEntero",
  "nDecimal",
  "cadena",
  "prTrue",
  "prFalse",
  "charNormal",
  "plus",
  "minus",
  "per",
  "div",
  "prExponent",
  "prMod",
  "leftPar",
  "rightPar"
  };
}

